version: "3.8"

services:
    django:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/home/myuser/code
        ports:
            - "8000:8000"
        env_file:
            - ./.env
        depends_on:
            - pgdb
    pgdb:
        image: postgres:12-alpine
        container_name: pgdb
        env_file:
            - ./.env
        ports:
            - "5432:5432"
        expose:
            - 5432
        volumes:
            - pgdata:/var/lib/postgresql/data/

volumes:
    pgdata:
    code: