# Generated by Django 4.0.3 on 2022-03-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170426_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pergunta',
            options={'ordering': ['-criado_em']},
        ),
    ]
